### ISSUE TITLE
Design Chart CSPEC

### ISSUE THREAD

**Issue by matdenkas** [conrad-blucher-institute/Flare#8]
The CSPEC stands for Chart Specification, the CSPEC should be modeled of the DSPEC, a json file that encodes required information for executing a data pipeline.

The CSPEC for broadcast needs to include:
- Several Features including features from Semaphore
- Calls to Post processing classes
- Feature names to be referenced by the fronted
- CVS File name to be written to

**Comment by abeasley1722** [comment]
![Image](https://github.com/user-attachments/assets/adee6be0-a2c9-41df-a14e-647ba6437b7e)
